### ISSUE TITLE
更新了 抓不到t值了

### ISSUE THREAD

**Issue by ace18zz** [zc2638/ylgy#13]
打开stream后就没办法开始游戏了，只能停在首页。如果打开第一关之后再抓包，就什么也抓不到。

**Comment by zc2638** [comment]
https://github.com/zc2638/ylgy/blob/main/docs/stream.md

看下教程，应该证书没生效，或者缓存没清理

**Comment by zjs1224522500** [comment]
> https://github.com/zc2638/ylgy/blob/main/docs/stream.md
> 
> 看下教程，应该证书没生效，或者缓存没清理

确实是抓不到了，开启抓包，全部就只发 CONNECT 请求，不会发 GET，所以拿不到。不发 GET 很多界面都进不了了

**Comment by zc2638** [comment]
刚测试下了可用，请确认证书是否配置正确，以及是否清理了缓存。

https://github.com/zc2638/ylgy/blob/main/docs/stream.md#3-%E9%85%8D%E7%BD%AE-https-%E6%8A%93%E5%8C%85
