### ISSUE TITLE
Error: 请求失败: Get "https://cat-match.easygame2021.com/sheep/v1/game/game_over?rank_role=1&rank_score=1&rank_state=1&rank_time=564&skin=1": EOF

### ISSUE THREAD

**Issue by yongxingMa** [zc2638/ylgy#14]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/31605966/190536558-1f7c270b-b9de-4174-82ae-6d0963d0427d.png">

**Comment by zc2638** [comment]
再发多次请求看看

**Comment by zc2638** [comment]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/28284116/190538413-c476bbdd-fc9e-4ad4-9b80-6cc968872e2e.png">

刚测试没有问题，应该你的网络问题

**Comment by yongxingMa** [comment]
换了几台阿里云 腾讯云服务器

**Comment by yongxingMa** [comment]
![image](https://user-images.githubusercontent.com/31605966/190539848-f5c3eb1c-b5d9-43d3-83e4-5ee979d6d509.png)

**Comment by yongxingMa** [comment]
![image](https://user-images.githubusercontent.com/31605966/190540057-ad5f2e87-50eb-4f10-948f-31e3c90a7a02.png)

**Comment by zc2638** [comment]
刷的太多，对方服务器可能崩了，返回 502 / 503，建议迟一些再尝试

**Comment by yongxingMa** [comment]
> 刷的太多，对方服务器可能崩了，返回 502 / 503，建议迟一些再尝试

好的大佬，太能刷了
