### ISSUE TITLE
提示请求失败，麻烦大佬指点一下

### ISSUE THREAD

**Issue by kraylv** [zc2638/ylgy#18]
调用总提示系统找不到指定路径
![123](https://user-images.githubusercontent.com/99251613/190569033-f53159d1-20f0-4464-aac1-fc18d433ec7d.jpg)
请问大佬是这样使用吗，尖括号里替换为抓到的t下面的token

**Comment by kraylv** [comment]
![image](https://user-images.githubusercontent.com/99251613/190572373-dc013531-2777-49ee-98d6-84ac7e6857bc.png)
麻烦大佬指点一下

**Comment by zc2638** [comment]
参考 #15

**Comment by kraylv** [comment]
报509证书问题了

**Comment by dawven** [comment]
我咋个一直超时
