### ISSUE TITLE
好像换接口了

### ISSUE THREAD

**Issue by shikingram** [zc2638/ylgy#19]
Error: 请求失败: Get "https://cat-match.easygame2021.com/sheep/v1/game/game_over?rank_role=1&rank_score=1&rank_state=1&rank_time=978&skin=1": dial tcp 49.233.99.201:443: i/o timeout

**Comment by zc2638** [comment]
参考 #15

**Comment by shikingram** [comment]
> 参考 #15

哈哈哈
