### ISSUE TITLE
无法获取t值怎么办啊哥哥

### ISSUE THREAD

**Issue by foolishma** [zc2638/ylgy#23]

**Comment by becarefulo0o** [comment]
我是用苹果才弄到的

**Comment by foolishma** [comment]
> 我是用苹果才弄到的

后面那个命令怎么执行，我的直接不识别ylgy这个命令

**Comment by yachenfeng00** [comment]
> 我是用苹果才弄到的

我的stream里 只有一个connect和head，head里是host，useragent，没看到token啊

**Comment by foolishma** [comment]
> > 我是用苹果才弄到的
> 
> 我的stream里 只有一个connect和head，head里是host，useragent，没看到token啊

应该是你没抓取到，点开排行榜，再点好友排行榜，再点历史排行榜直到出数据就可以停止抓包了

**Comment by y4code** [comment]
不要看static 域名，只看json 返回结果，一下子就找到了

**Comment by Dicer-Zz** [comment]
需要抓https包，需要在stream里下载信任文件
