### ISSUE TITLE
IOS -Stream 里面获取不到对应的token

### ISSUE THREAD

**Issue by MentosL** [zc2638/ylgy#24]
IOS -Stream 里面获取不到对应的token

**Comment by wuweijian1997** [comment]
要下载安装信任证书才能抓https的包

**Comment by MentosL** [comment]
下载安装了    进入小程序里面也玩了一局，抓取的没看到 head里面的t

**Comment by zhenghaohong** [comment]
我也一样 用stream 获取不到t值

**Comment by y4code** [comment]
注意域名过滤，不要选带static 的域名，然后选择 只看 json返回

**Comment by zhenghaohong** [comment]
Mr.Z
***@***.***



&nbsp;
好的 已经可以了 非常感谢您


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zc2638/ylgy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zc2638/ylgy] IOS -Stream 里面获取不到对应的token (Issue #24)





 
注意域名过滤，不要选带static 的域名，然后选择 只看 json返回

**Comment by Dicer-Zz** [comment]
同问，stream抓包没找到token

**Comment by doudio** [comment]
我也是没看到t, 会不会作者紧急跟新了呀!

**Comment by MentosL** [comment]
目前进小程序里面就很卡，再点击全国排行和进去玩一局之后、出来发现对应的stream里面关于此域名底下的请求都没响应数据，对应的请求头内也没有看到对应的t
