### ISSUE TITLE
ylgy 命令无法识别，怎么搞？指导一下

### ISSUE THREAD

**Issue by foolishma** [zc2638/ylgy#25]

**Comment by saowu** [comment]
go build cmd/ylgy/main.go  
./main -t --token <your-custom-token>

**Comment by foolishma** [comment]
> go build cmd/ylgy/main.go

？？go不识别

**Comment by fzdwx** [comment]
@foolishma  https://www.baidu.com/s?wd=go%E8%AF%AD%E8%A8%80%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B

**Comment by zc2638** [comment]
到这里下载
https://github.com/zc2638/ylgy/releases

**Comment by saowu** [comment]
哈哈哈哈

**Comment by fzdwx** [comment]
取这id不是没原因的。。

**Comment by foolishma** [comment]
> 取这id不是没原因的。。

哈哈哈哈，没有那个锅这玩意儿。。。

**Comment by yachenfeng00** [comment]
在windows下 需要 安装go环境吗

> > 取这id不是没原因的。。
> 
> 哈哈哈哈，没有那个锅这玩意儿。。。

**Comment by foolishma** [comment]
> 在windows下 需要 安装go环境吗
> 
> > > 取这id不是没原因的。。
> > 
> > 
> > 哈哈哈哈，没有那个锅这玩意儿。。。

是的，不然怎么玩？

**Comment by foolishma** [comment]
> [#25 (comment)](https://github.com/zc2638/ylgy/issues/25#issuecomment-1249013645) 作者已经编译好啦


> [#25 (comment)](https://github.com/zc2638/ylgy/issues/25#issuecomment-1249013645) 作者已经编译好啦

编译的这个东西怎么用

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/190583929-417bb31b-0a56-456f-8c17-46fe476525b0.png)

解压了直接用。

**Comment by foolishma** [comment]
> ![image](https://user-images.githubusercontent.com/65269574/190583929-417bb31b-0a56-456f-8c17-46fe476525b0.png)
> 
> 解压了直接用。

我电脑wins_64位的，下载的那个提示我版本不对

**Comment by foolishma** [comment]
> 到这里下载 https://github.com/zc2638/ylgy/releases

我下载的不会用啊。。。。。。可以再喂一喂么

**Comment by fzdwx** [comment]
................. 终端里面运行

**Comment by zhaozekai456** [comment]
> > 到这里下载 https://github.com/zc2638/ylgy/releases
> 
> 我下载的不会用啊。。。。。。可以再喂一喂么
我这个下载提示版本不适配诶

**Comment by foolishma** [comment]
> ................. 终端里面运行

运行了提示ylgy不识别噻。。。。

**Comment by fzdwx** [comment]
把go下了吧。

**Comment by foolishma** [comment]
> 把go下了吧。

go下了，环境配了，安装包下载的[ylgy_windows_armv7.zip](https://github.com/zc2638/ylgy/releases/download/v0.0.2/ylgy_windows_armv7.zip)
[ylgy_windows_arm64.zip](https://github.com/zc2638/ylgy/releases/download/v0.0.2/ylgy_windows_arm64.zip)
都提示  无法在此电脑运行

**Comment by zc2638** [comment]
> 运行了提示ylgy不识别噻。。。。

直接拖到终端里

**Comment by foolishma** [comment]
> > 运行了提示ylgy不识别噻。。。。
> 
> 直接拖到终端里

提示无法在此电脑运行，是不是和winds版本有关，我的是winds11

**Comment by zc2638** [comment]
看下CPU，下 x86_64 或者 i386 的
@foolishma

**Comment by foolishma** [comment]
> 看下CPU，下 x86_64 或者 i386 的 @foolishma

i386的可以，感谢，没有皮肤奖励吗
