### ISSUE TITLE
老哥我用postman的话，通关次数的参数要咋加

### ISSUE THREAD

**Issue by diorszzz** [zc2638/ylgy#28]

**Comment by canbingzt** [comment]
curl -H "t: $token" -H "Referer: https://servicewechat.com/wx141bfb9b73c970a9/page-frame.html" "https://cat-match.easygame2021.com/sheep/v1/game/game_over?rank_role=1&rank_score=1&rank_state=1&rank_time=565&skin=1"

time可以修改

**Comment by zc2638** [comment]
请求几次，通关几次
