### ISSUE TITLE
请求失败: Get... 什么情况?

### ISSUE THREAD

**Issue by Yyouzi1** [zc2638/ylgy#29]
请求失败: Get "https://cat-match.easygame2021.com/sheep/v1/game/game_over?rank_role=1&rank_score=1&rank_state=1&rank_time=171&skin=1": read tcp 172.27.58.121:64446->82.157.159.15:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by zc2638** [comment]
参考 #15 一样的情况
