### ISSUE TITLE
win10 ylgy.exe执行不了

### ISSUE THREAD

**Issue by zhouwenquna663** [zc2638/ylgy#35]
![微信图片_20220916204633](https://user-images.githubusercontent.com/34540101/190642013-789a7778-1ff9-4425-a6cd-58a725ed3089.png)

**Comment by zhouwenquna663** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zc2638/ylgy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月17日(星期六) 凌晨0:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zc2638/ylgy] win10 ylgy.exe执行不了 (Issue #35)





 
win+r cmd 把ylgy.exe放cmd窗口里面的目录 复制命令行进去 即可

**Comment by karmawws** [comment]
> win+r cmd 把ylgy.exe放cmd窗口里面的目录 复制命令行进去 即可

请问cmd里要输入什么呀 不知道怎么输入token

**Comment by zc2638** [comment]
参考 #25
