### ISSUE TITLE
出现如下错误

### ISSUE THREAD

**Issue by liuzeaa** [zc2638/ylgy#43]
Error: 请求失败: Get "https://cat-match.easygame2021.com/sheep/v1/game/game_over?rank_role=1&rank_score=1&rank_state=1&rank_time=528&skin=1": http: server gave HTTP response to HTTPS client

**Comment by karmawws** [comment]
请问是怎样输入到cmd窗口里的...
谢谢

**Comment by liuzeaa** [comment]
![image](https://user-images.githubusercontent.com/15085161/190912109-875bd291-7672-48cd-829d-1e22e6e98b1f.png)
