### ISSUE TITLE
现在已经失效，现在运行通过只增加话题通关次数，并不加入羊群了。

### ISSUE THREAD

**Issue by wsjackys** [zc2638/ylgy#50]
一切运行正常，运行成功后在按的名片里面每日话题通关数增加，但是期间加入羊群依旧为0。估计羊了个样更改了接口。

**Comment by xiak** [comment]
在游戏里面发现个新的 BUG ，可以通过 GET /sheep/v1/game/user_rank_info?uid=xxxxxx 增加加入羊群次数

**Comment by zc2638** [comment]
暂时使用 抓包重写 方式通关，查看 README
https://github.com/zc2638/ylgy/blob/fc7c17c7f59556c40abd0ea071ce5d138441ddec/README.md

**Comment by wyp010428** [comment]
现在可以通过修改blocktyype来重写，参考https://github.com/wyp010428/ylgy920
