### ISSUE TITLE
采用新的方式通关了，但是在榜单上没有

### ISSUE THREAD

**Issue by CoXier** [zc2638/ylgy#51]
采用 charles 重写/map local 后，虽然成功闯关了，但是在朋友圈列表上看不到。仍然显示 0
![image](https://user-images.githubusercontent.com/18747437/191012647-aa01f5ed-f4d5-4ef0-b91c-d3846dbf81dd.png)

**Comment by VoltaDusk** [comment]
+1，Charles重写也只能本地通关了，朋友圈没更新
