### ISSUE TITLE
rewrite方法

### ISSUE THREAD

**Issue by GnaixEuy** [zc2638/ylgy#57]
替换值是否存在时效性，9月20日实用已失效，大佬可以解释一下这个是如何获取对应值的吗

**Comment by wyp010428** [comment]
重写方法与刷次数方法参考 https://github.com/wyp010428/ylgy920

**Comment by Geek-sky** [comment]
有无用http catcher 的大佬，可以解释下如何在http catcher中rewrite map_md5

**Comment by wyp010428** [comment]
> 有无用http catcher 的大佬，可以解释下如何在http catcher中rewrite map_md5

重写map_md5通关后你的MatchPlayInfo是不能通关校验的，不会增加次数

**Comment by zc2638** [comment]
使用 v0.0.5 版本
