### ISSUE TITLE
有winds_i386的Release包么

### ISSUE THREAD

**Issue by foolishma** [zc2638/ylgy#64]

**Comment by zc2638** [comment]
https://github.com/zc2638/ylgy/releases/download/v0.0.5/ylgy_windows_i386.zip

**Comment by foolishma** [comment]
> https://github.com/zc2638/ylgy/releases/download/v0.0.5/ylgy_windows_i386.zip

有没有刷皮肤的

**Comment by foolishma** [comment]
> > https://github.com/zc2638/ylgy/releases/download/v0.0.5/ylgy_windows_i386.zip
> 
> 有没有刷皮肤的

获取map信息失败

**Comment by foolishma** [comment]
> https://github.com/zc2638/ylgy/releases/download/v0.0.5/ylgy_windows_i386.zip

刷完第一次后，再刷，次数不变了，这个是因为被修复了吗
